apiVersion: v1
kind: Pod
metadata:
  name: ibmedical
  labels:
    name: ibmedical
spec:
  containers:
  - name: ibmmedical-app
    image: quay.io/ahamed73/ibmedical:0.0.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
  imagePullSecrets:
    - name: quay
