apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cni.projectcalico.org/containerID: 545755bbc53c88ad1bf2ce97d432e18e00f93276c08c3e5e8da0f384e11dd35a
      cni.projectcalico.org/podIP: 172.30.187.87/32
      cni.projectcalico.org/podIPs: 172.30.187.87/32
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "k8s-pod-network",
            "ips": [
                "172.30.187.87"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "k8s-pod-network",
            "ips": [
                "172.30.187.87"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/scc: restricted
    creationTimestamp: "2022-07-19T14:41:24Z"
    generateName: ibmedical-df95f6479-
    labels:
      deployment: ibmedical
      pod-template-hash: df95f6479
    name: ibmedical-df95f6479-7rclv
    namespace: ibmedical
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: ibmedical-df95f6479
      uid: 33f9acc4-6fec-449b-9033-d893ce5dac0c
    resourceVersion: "361705"
    uid: db8c7ebb-8e59-4e63-a6b2-bfbaea7eb094
  spec:
    containers:
    - image: quay.io/ahamed73/ibmedical@sha256:c6af00da777665bf9d791f1bda31698d9babc5e9882023b35c51fa4b5ccbf7aa
      imagePullPolicy: IfNotPresent
      name: ibmedical
      ports:
      - containerPort: 6000
        protocol: TCP
      - containerPort: 8000
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1000670000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-zphzh
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    imagePullSecrets:
    - name: default-dockercfg-l8n6g
    nodeName: 10.149.114.155
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000670000
      seLinuxOptions:
        level: s0:c26,c10
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-zphzh
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-07-19T14:41:24Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-07-19T14:41:26Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-07-19T14:41:26Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-07-19T14:41:24Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://e39b2328deb51a4a125cb18ec6c124a862ea2c790f6a511f4f433d4f0323722d
      image: quay.io/ahamed73/ibmedical:0.0.1
      imageID: quay.io/ahamed73/ibmedical@sha256:c6af00da777665bf9d791f1bda31698d9babc5e9882023b35c51fa4b5ccbf7aa
      lastState: {}
      name: ibmedical
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-07-19T14:41:26Z"
    hostIP: 10.149.114.155
    phase: Running
    podIP: 172.30.187.87
    podIPs:
    - ip: 172.30.187.87
    qosClass: BestEffort
    startTime: "2022-07-19T14:41:24Z"
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-07-19T15:22:21Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: ibmedical
      app.kubernetes.io/component: ibmedical
      app.kubernetes.io/instance: ibmedical
    name: ibmedical
    namespace: ibmedical
    resourceVersion: "379276"
    uid: 8dd3fca5-97e1-495b-8d9d-c71112d037b9
  spec:
    clusterIP: 172.21.148.0
    clusterIPs:
    - 172.21.148.0
    externalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32310
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deployment: ibmedical
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 169.55.76.219
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"ibmedical:0.0.1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ibmedical\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2022-07-19T14:41:24Z"
    generation: 2
    labels:
      app: ibmedical
      app.kubernetes.io/component: ibmedical
      app.kubernetes.io/instance: ibmedical
    name: ibmedical
    namespace: ibmedical
    resourceVersion: "361715"
    uid: 0f455de6-1733-4b6f-87dc-e4ecf5ed77b3
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: ibmedical
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: ibmedical
      spec:
        containers:
        - image: quay.io/ahamed73/ibmedical@sha256:c6af00da777665bf9d791f1bda31698d9babc5e9882023b35c51fa4b5ccbf7aa
          imagePullPolicy: IfNotPresent
          name: ibmedical
          ports:
          - containerPort: 6000
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-07-19T14:41:26Z"
      lastUpdateTime: "2022-07-19T14:41:26Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-07-19T14:41:24Z"
      lastUpdateTime: "2022-07-19T14:41:26Z"
      message: ReplicaSet "ibmedical-df95f6479" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"ibmedical:0.0.1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ibmedical\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2022-07-19T14:41:24Z"
    generation: 2
    labels:
      deployment: ibmedical
      pod-template-hash: 6669dcc465
    name: ibmedical-6669dcc465
    namespace: ibmedical
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: ibmedical
      uid: 0f455de6-1733-4b6f-87dc-e4ecf5ed77b3
    resourceVersion: "361713"
    uid: f3983f8b-c799-4737-8891-c517df246715
  spec:
    replicas: 0
    selector:
      matchLabels:
        deployment: ibmedical
        pod-template-hash: 6669dcc465
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: ibmedical
          pod-template-hash: 6669dcc465
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: ibmedical
          ports:
          - containerPort: 6000
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "2"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"ibmedical:0.0.1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ibmedical\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2022-07-19T14:41:24Z"
    generation: 1
    labels:
      deployment: ibmedical
      pod-template-hash: df95f6479
    name: ibmedical-df95f6479
    namespace: ibmedical
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: ibmedical
      uid: 0f455de6-1733-4b6f-87dc-e4ecf5ed77b3
    resourceVersion: "361707"
    uid: 33f9acc4-6fec-449b-9033-d893ce5dac0c
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: ibmedical
        pod-template-hash: df95f6479
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: ibmedical
          pod-template-hash: df95f6479
      spec:
        containers:
        - image: quay.io/ahamed73/ibmedical@sha256:c6af00da777665bf9d791f1bda31698d9babc5e9882023b35c51fa4b5ccbf7aa
          imagePullPolicy: IfNotPresent
          name: ibmedical
          ports:
          - containerPort: 6000
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: "2022-07-19T14:41:24Z"
    creationTimestamp: "2022-07-19T14:41:24Z"
    generation: 2
    labels:
      app: ibmedical
      app.kubernetes.io/component: ibmedical
      app.kubernetes.io/instance: ibmedical
    name: ibmedical
    namespace: ibmedical
    resourceVersion: "361664"
    uid: 01a245f6-9746-46fd-9e14-21e2cdcfa4ab
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/ahamed73/ibmedical:0.0.1
      from:
        kind: DockerImage
        name: quay.io/ahamed73/ibmedical:0.0.1
      generation: 2
      importPolicy: {}
      name: 0.0.1
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/ibmedical/ibmedical
    tags:
    - items:
      - created: "2022-07-19T14:41:24Z"
        dockerImageReference: quay.io/ahamed73/ibmedical@sha256:c6af00da777665bf9d791f1bda31698d9babc5e9882023b35c51fa4b5ccbf7aa
        generation: 2
        image: sha256:c6af00da777665bf9d791f1bda31698d9babc5e9882023b35c51fa4b5ccbf7aa
      tag: 0.0.1
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: "2022-07-19T15:23:31Z"
    labels:
      app: ibmedical
      app.kubernetes.io/component: ibmedical
      app.kubernetes.io/instance: ibmedical
    name: ibmedical
    namespace: ibmedical
    resourceVersion: "379734"
    uid: 36e02075-97dc-4e5a-be1d-f2d00764b09f
  spec:
    host: ibmedical-ibmedical.itzroks-664001oy6r-hpa3dm-4b4a324f027aea19c5cbc0c3275c4656-0000.us-east.containers.appdomain.cloud
    port:
      targetPort: 8000
    to:
      kind: Service
      name: ibmedical
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2022-07-19T15:23:31Z"
        status: "True"
        type: Admitted
      host: ibmedical-ibmedical.itzroks-664001oy6r-hpa3dm-4b4a324f027aea19c5cbc0c3275c4656-0000.us-east.containers.appdomain.cloud
      routerCanonicalHostname: router-default.itzroks-664001oy6r-hpa3dm-4b4a324f027aea19c5cbc0c3275c4656-0000.us-east.containers.appdomain.cloud
      routerName: default
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
